// src/app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { CartProvider } from "@/lib/CartContext";
import CartNavLink from "@/components/CartNavLink";
// ⭐️ NEW IMPORT: Dialog component
import RestaurantConflictDialog from "@/components/RestaurantConflictDialog";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Food-Delivery App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          {/* Global Navbar */}
          <nav className="flex justify-between items-center px-8 py-6 bg-white shadow-sm">
            <Link
              href="/"
              className="text-2xl font-extrabold text-orange-600 tracking-tight hover:text-orange-700 transition"
            >
              QuickBite
            </Link>

            {/* Optional right-side nav items */}
            <div className="flex items-center space-x-4">
              <div className="space-x-6 hidden sm:flex">
                <Link
                  href="/users/restaurants"
                  className="text-gray-700 hover:text-orange-600 transition"
                >
                  Restaurants
                </Link>
                <Link
                  href="#"
                  className="text-gray-700 hover:text-orange-600 transition"
                >
                  Drivers
                </Link>
                <Link
                  href="/about"
                  className="text-gray-700 hover:text-orange-600 transition"
                >
                  About
                </Link>
              </div>

              <CartNavLink />

              <Link
                href="/login"
                className="bg-orange-500 hover:bg-orange-600 text-white px-5 py-2 rounded-xl shadow-md transition"
              >
                Login / Signup
              </Link>
            </div>
          </nav>

          {/* Page-specific content */}
          <main>{children}</main>

          {/* ⭐️ CONFLICT DIALOG RENDERED HERE (appears over everything) ⭐️ */}
          <RestaurantConflictDialog />
        </CartProvider>
      </body>
    </html>
  );
}
